numbers = [4,2,9,1,5,6]
length = len(numbers)
print(f"Length of numbers list: {length}")
total_sum = sum(numbers)
print(f"Sum of numbers list: {total_sum}")
max_value = max(numbers)
print(f"Maximum value: {max_value}")
min_value = min(numbers)
print(f"Minimum value: {min_value}")
sorted_numbers = sorted(numbers)
print(f"Sorted numbers: {sorted_numbers}")
bool_list = [False, True, False]
any_true = any(bool_list)
print(f"Any True in bool_list: {any_true}")
all_true = all(bool_list)
print(f"All True in bool_list: {all_true}")
string = "hello"
char_list = list(string)
print(f"List of characters from string: {char_list}")
reversed_numbers = list(reversed(numbers))
print(f"Reversed numbers: {reversed_numbers}")
enumerated_numbers = list(enumerate(numbers))
print(f"Enumerated numbers: {enumerated_numbers}")